
package Views;

import Controllers.PrincipalController;
import java.awt.Color;

public class adminNewCourtsForm extends javax.swing.JFrame {

    /**
     * Creates new form adminNewCourtsForm
     */
    public adminNewCourtsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnInsertCourtForm.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturnCourtPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNameInsertCourtForm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUbicationInsertCourtForm = new javax.swing.JTextField();
        btnInsertCourtForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReturnCourtPanel.setText("Tornar ...");
        btnReturnCourtPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnCourtPanelActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        txtNameInsertCourtForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameInsertCourtFormFocusLost(evt);
            }
        });
        txtNameInsertCourtForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameInsertCourtFormActionPerformed(evt);
            }
        });
        txtNameInsertCourtForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameInsertCourtFormKeyTyped(evt);
            }
        });

        jLabel2.setText("Ubicació");

        txtUbicationInsertCourtForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUbicationInsertCourtFormFocusLost(evt);
            }
        });
        txtUbicationInsertCourtForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicationInsertCourtFormActionPerformed(evt);
            }
        });
        txtUbicationInsertCourtForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbicationInsertCourtFormKeyTyped(evt);
            }
        });

        btnInsertCourtForm.setText("Crear pista");
        btnInsertCourtForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertCourtFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturnCourtPanel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1)
                        .addGap(0, 198, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnInsertCourtForm, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(txtNameInsertCourtForm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(txtUbicationInsertCourtForm, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReturnCourtPanel)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameInsertCourtForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUbicationInsertCourtForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnInsertCourtForm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnCourtPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnCourtPanelActionPerformed
        PrincipalController.returnNewFormCourtPanel();
    }//GEN-LAST:event_btnReturnCourtPanelActionPerformed

    private void txtNameInsertCourtFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameInsertCourtFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameInsertCourtFormActionPerformed

    private void txtUbicationInsertCourtFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicationInsertCourtFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicationInsertCourtFormActionPerformed

    private void btnInsertCourtFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertCourtFormActionPerformed
        String name = txtNameInsertCourtForm.getText();
        String ubication = txtUbicationInsertCourtForm.getText();
        PrincipalController.insertCourt(name, ubication);
    }//GEN-LAST:event_btnInsertCourtFormActionPerformed

    private void txtNameInsertCourtFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameInsertCourtFormFocusLost
        String name = txtNameInsertCourtForm.getText().trim();
        String namePattern = "^Pista [A-Za-z\\s]+$";

        if (name.matches(namePattern)) {
            txtNameInsertCourtForm.setBackground(Color.GREEN);
        }
        
    }//GEN-LAST:event_txtNameInsertCourtFormFocusLost

    private void txtNameInsertCourtFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameInsertCourtFormKeyTyped
        String name = txtNameInsertCourtForm.getText().trim();
        String namePattern = "^Pista [A-Za-z\\s]+$";

        if (!name.matches(namePattern)) {
            txtNameInsertCourtForm.setBackground(Color.RED);
        }
        checkData();
    }//GEN-LAST:event_txtNameInsertCourtFormKeyTyped

    private void txtUbicationInsertCourtFormKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbicationInsertCourtFormKeyTyped
        String ubication = txtUbicationInsertCourtForm.getText().trim();
        String ubicationPattern = "^Sector \\d+$";

        if (!ubication.matches(ubicationPattern)) {
            txtUbicationInsertCourtForm.setBackground(Color.RED);
        }
        checkData();
    }//GEN-LAST:event_txtUbicationInsertCourtFormKeyTyped

    private void txtUbicationInsertCourtFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUbicationInsertCourtFormFocusLost
        String ubication = txtUbicationInsertCourtForm.getText().trim();
        String ubicationPattern = "^Sector \\d+$";

        if (ubication.matches(ubicationPattern)) {
            txtUbicationInsertCourtForm.setBackground(Color.GREEN);
        }
        checkData();
    }//GEN-LAST:event_txtUbicationInsertCourtFormFocusLost

    private void checkData() {
        String name = txtNameInsertCourtForm.getText().trim();
        String namePattern = "^Pista [A-Za-z\\s]+$";
        String ubication = txtUbicationInsertCourtForm.getText().trim();
        String ubicationPattern = "^Sector \\d+$";
        
        if (!name.matches(namePattern) || !ubication.matches(ubicationPattern)) {
            btnInsertCourtForm.setEnabled(false);
        }
        else {
            btnInsertCourtForm.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminNewCourtsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminNewCourtsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminNewCourtsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminNewCourtsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminNewCourtsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInsertCourtForm;
    public javax.swing.JButton btnReturnCourtPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtNameInsertCourtForm;
    public javax.swing.JTextField txtUbicationInsertCourtForm;
    // End of variables declaration//GEN-END:variables
}
