
package Views;

import Controllers.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class adminUsersDashboard extends javax.swing.JFrame {

    /**
     * Creates new form insertForm
     */
    public adminUsersDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        tblUsers.setModel(modelo);
        PrincipalController.loadTblUser(modelo);   
        btnBackUser.setBackground(null);
        btnBackUser.setContentAreaFilled(false);
        btnBackUser.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnDeactivateUserForm = new javax.swing.JButton();
        btnResetPasswdUserForm = new javax.swing.JButton();
        txtSearchUser = new javax.swing.JTextField();
        btnActivateUserForm = new javax.swing.JButton();
        btnInsertUserForm = new javax.swing.JButton();
        btnUpdateUserForm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JLabelLogo = new javax.swing.JLabel();
        btnBackUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 229, 255));
        setPreferredSize(new java.awt.Dimension(575, 445));
        setResizable(false);

        tblUsers.setBackground(new java.awt.Color(255, 255, 255));
        tblUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblUsers.setForeground(new java.awt.Color(30, 30, 30));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Cognom", "DNI", "Correu", "Telèfon", "Estat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setGridColor(new java.awt.Color(30, 30, 30));
        tblUsers.setIntercellSpacing(new java.awt.Dimension(10, 0));
        tblUsers.setSelectionBackground(new java.awt.Color(255, 255, 225));
        jScrollPane1.setViewportView(tblUsers);

        btnDeactivateUserForm.setBackground(new java.awt.Color(0, 0, 153));
        btnDeactivateUserForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeactivateUserForm.setForeground(new java.awt.Color(255, 255, 255));
        btnDeactivateUserForm.setText("Desactivar");
        btnDeactivateUserForm.setBorder(null);
        btnDeactivateUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateUserFormActionPerformed(evt);
            }
        });

        btnResetPasswdUserForm.setBackground(new java.awt.Color(0, 0, 153));
        btnResetPasswdUserForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPasswdUserForm.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPasswdUserForm.setText("Resetejar Passwd");
        btnResetPasswdUserForm.setBorder(null);
        btnResetPasswdUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswdUserFormActionPerformed(evt);
            }
        });

        txtSearchUser.setBackground(new java.awt.Color(255, 255, 255));
        txtSearchUser.setForeground(new java.awt.Color(30, 30, 30));
        txtSearchUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearchUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchUserCaretUpdate(evt);
            }
        });
        txtSearchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyTyped(evt);
            }
        });

        btnActivateUserForm.setBackground(new java.awt.Color(0, 0, 153));
        btnActivateUserForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActivateUserForm.setForeground(new java.awt.Color(255, 255, 255));
        btnActivateUserForm.setText("Activar");
        btnActivateUserForm.setBorder(null);
        btnActivateUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateUserFormActionPerformed(evt);
            }
        });

        btnInsertUserForm.setBackground(new java.awt.Color(0, 0, 153));
        btnInsertUserForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertUserForm.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertUserForm.setText("Agregar");
        btnInsertUserForm.setBorder(null);
        btnInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertUserFormActionPerformed(evt);
            }
        });

        btnUpdateUserForm.setBackground(new java.awt.Color(0, 0, 153));
        btnUpdateUserForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateUserForm.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUserForm.setText("Modificar");
        btnUpdateUserForm.setBorder(null);
        btnUpdateUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserFormActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Filtra per DNI:");

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(575, 455));

        JLabelLogo.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\Images\\logoPadelAGWhite.png"));

        btnBackUser.setBackground(new java.awt.Color(255, 255, 255));
        btnBackUser.setForeground(new java.awt.Color(255, 255, 255));
        btnBackUser.setText("Tornar ...");
        btnBackUser.setBorder(null);
        btnBackUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackUser, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("LLISTAT D'USUARIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtSearchUser))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResetPasswdUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeactivateUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActivateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetPasswdUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnActivateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeactivateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUserActionPerformed
        PrincipalController.returnUserPanel();
    }//GEN-LAST:event_btnBackUserActionPerformed

    private void btnDeactivateUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            System.out.print(selectedRow);
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            PrincipalController.deactivateUser(idUser);
            loadTable();
        }
    }//GEN-LAST:event_btnDeactivateUserFormActionPerformed

    private void btnActivateUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            System.out.print(selectedRow);
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            PrincipalController.activateUser(idUser);
            loadTable();
        }
    }//GEN-LAST:event_btnActivateUserFormActionPerformed

    private void btnResetPasswdUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswdUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            System.out.print(selectedRow);
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            PrincipalController.resetPasswdUser(idUser);
        }
    }//GEN-LAST:event_btnResetPasswdUserFormActionPerformed

    private void btnUpdateUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
        JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            String nom = (String) modelTable.getValueAt(selectedRow, 1);
            String cognom = (String) modelTable.getValueAt(selectedRow, 2);
            String correu = (String) modelTable.getValueAt(selectedRow, 4);
            String telefon = (String) modelTable.getValueAt(selectedRow, 5);

            PrincipalController.showUpdateFormUserPanel(idUser, nom, cognom, correu, telefon);
        }

    }//GEN-LAST:event_btnUpdateUserFormActionPerformed

    private void btnInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertUserFormActionPerformed
        PrincipalController.showNewFormUserPanel();
    }//GEN-LAST:event_btnInsertUserFormActionPerformed

    private void txtSearchUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserKeyTyped

    private void txtSearchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyReleased
        DefaultTableModel modelo = new DefaultTableModel();
        tblUsers.setModel(modelo);
        String where = txtSearchUser.getText();
        PrincipalController.loadTblUserWhere(modelo, where);
    }//GEN-LAST:event_txtSearchUserKeyReleased

    private void txtSearchUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchUserCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminUsersDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLogo;
    private javax.swing.JButton btnActivateUserForm;
    private javax.swing.JButton btnBackUser;
    private javax.swing.JButton btnDeactivateUserForm;
    private javax.swing.JButton btnInsertUserForm;
    private javax.swing.JButton btnResetPasswdUserForm;
    private javax.swing.JButton btnUpdateUserForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearchUser;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        DefaultTableModel modelo = new DefaultTableModel();
        tblUsers.setModel(modelo);
        PrincipalController.loadTblUserWhere(modelo, txtSearchUser.getText());
    }
}
