
package Views;

import Controllers.PrincipalController;
import java.awt.Color;
import javax.swing.JOptionPane;

public class adminNewUsersForm extends javax.swing.JFrame {

    /**
     * Creates new form adminNewUsersForm
     */
    public adminNewUsersForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnInsertUserForm.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNameInsertUserForm = new javax.swing.JTextField();
        txtSurnameInsertUserForm = new javax.swing.JTextField();
        txtMailInsertUserForm = new javax.swing.JTextField();
        txtPhoneInsertUserForm = new javax.swing.JTextField();
        txtDniInsertUserForm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInsertUserForm = new javax.swing.JButton();
        btnReturnUserPanelActionPerformed = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPasswdInsertUserForm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom:");

        txtNameInsertUserForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameInsertUserFormFocusLost(evt);
            }
        });
        txtNameInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameInsertUserFormActionPerformed(evt);
            }
        });

        txtSurnameInsertUserForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSurnameInsertUserFormFocusLost(evt);
            }
        });
        txtSurnameInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameInsertUserFormActionPerformed(evt);
            }
        });

        txtMailInsertUserForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailInsertUserFormFocusLost(evt);
            }
        });
        txtMailInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailInsertUserFormActionPerformed(evt);
            }
        });

        txtPhoneInsertUserForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneInsertUserFormFocusLost(evt);
            }
        });
        txtPhoneInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneInsertUserFormActionPerformed(evt);
            }
        });

        txtDniInsertUserForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDniInsertUserFormFocusLost(evt);
            }
        });
        txtDniInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniInsertUserFormActionPerformed(evt);
            }
        });

        jLabel2.setText("Cognom:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Correu:");

        jLabel5.setText("Telèfon:");

        btnInsertUserForm.setText("Registrar");
        btnInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertUserFormActionPerformed(evt);
            }
        });

        btnReturnUserPanelActionPerformed.setText("Tornar ...");
        btnReturnUserPanelActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnUserPanelActionPerformedActionPerformed(evt);
            }
        });

        jLabel6.setText("Contrasenya:");

        txtPasswdInsertUserForm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswdInsertUserFormFocusLost(evt);
            }
        });
        txtPasswdInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswdInsertUserFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReturnUserPanelActionPerformed))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsertUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNameInsertUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtSurnameInsertUserForm)
                                    .addComponent(txtDniInsertUserForm)
                                    .addComponent(txtMailInsertUserForm)
                                    .addComponent(txtPhoneInsertUserForm)
                                    .addComponent(txtPasswdInsertUserForm))))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReturnUserPanelActionPerformed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSurnameInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDniInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMailInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPasswdInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(12, 12, 12)
                .addComponent(btnInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertUserFormActionPerformed
        String name = txtNameInsertUserForm.getText();
        String surname = txtSurnameInsertUserForm.getText();
        String dni = txtDniInsertUserForm.getText();
        String mail = txtMailInsertUserForm.getText();
        String phone = txtPhoneInsertUserForm.getText();
        String passwd = txtPasswdInsertUserForm.getText();

        PrincipalController.insertUser(name, surname, dni, mail, phone, passwd);
    }//GEN-LAST:event_btnInsertUserFormActionPerformed

    private void txtNameInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameInsertUserFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameInsertUserFormActionPerformed

    private void txtSurnameInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameInsertUserFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameInsertUserFormActionPerformed

    private void txtDniInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniInsertUserFormActionPerformed
        // Obtiene el valor del campo de texto DNI y elimina espacios en blanco.
//        String dni = txtDniInsertUserForm.getText().trim();
//        System.out.println(dni);
//
//        // Define una expresión regular para verificar que el DNI tenga 8 dígitos seguidos de una letra.
//        String dniPattern = "\\d{8}[A-Za-z]";
//
//        if (dni.matches(dniPattern)) {
//            // El DNI es válido (cumple con el patrón).
//            // Puedes realizar alguna acción, como cambiar el color del campo o mostrar un mensaje de validación.
//            txtDniInsertUserForm.setBackground(Color.GREEN);
//            // También puedes habilitar el botón para registrar si todos los campos son válidos.
//            habilitarBotonRegistro();
//        } else {
//            // El DNI no es válido, muestra un mensaje de error.
//            JOptionPane.showMessageDialog(this, "El DNI ingresado no es válido. Debe contener 8 números seguidos de una letra.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
//            // Puedes restaurar el color del campo a su estado original.
//            txtDniInsertUserForm.setBackground(Color.WHITE);
//            // También puedes deshabilitar el botón de registro si un campo es inválido.
//            deshabilitarBotonRegistro();
//        }

    }//GEN-LAST:event_txtDniInsertUserFormActionPerformed
    private void habilitarBotonRegistro() {
        btnInsertUserForm.setEnabled(true);
    }

    private void deshabilitarBotonRegistro() {
        btnInsertUserForm.setEnabled(false);
    }
    
    
    private void txtMailInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailInsertUserFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailInsertUserFormActionPerformed

    private void txtPhoneInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneInsertUserFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneInsertUserFormActionPerformed

    private void btnReturnUserPanelActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnUserPanelActionPerformedActionPerformed
        PrincipalController.returnNewFormUserPanel();
    }//GEN-LAST:event_btnReturnUserPanelActionPerformedActionPerformed

    private void txtPasswdInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswdInsertUserFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswdInsertUserFormActionPerformed

    private void txtDniInsertUserFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDniInsertUserFormFocusLost
        String dni = txtDniInsertUserForm.getText().trim();
        String dniPattern = "\\d{8}[A-Za-z]";

        if (dni.matches(dniPattern)) {
            txtDniInsertUserForm.setBackground(Color.GREEN);
            habilitarBotonRegistro();
        } else {
            JOptionPane.showMessageDialog(this, "El DNI introduit no és vàlid. Ha de contenir 8 numeros i una lletra final", "Error de Validació", JOptionPane.ERROR_MESSAGE);
            txtDniInsertUserForm.setBackground(Color.WHITE);
            deshabilitarBotonRegistro();
        }
    }//GEN-LAST:event_txtDniInsertUserFormFocusLost

    private void txtPhoneInsertUserFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneInsertUserFormFocusLost
        String phoneNumber = txtPhoneInsertUserForm.getText().trim();
    
        if (phoneNumber.matches("\\d+")) {
            txtPhoneInsertUserForm.setBackground(Color.GREEN);
            habilitarBotonRegistro();
        } else {
            JOptionPane.showMessageDialog(this, "El número de telèfon introduit no és vàlid. Ha de contenir només numeros.", "Error de Validació", JOptionPane.ERROR_MESSAGE);
            txtPhoneInsertUserForm.setBackground(Color.WHITE);
            deshabilitarBotonRegistro();
        }
    }//GEN-LAST:event_txtPhoneInsertUserFormFocusLost

    private void txtMailInsertUserFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailInsertUserFormFocusLost
        String email = txtMailInsertUserForm.getText().trim();
        String emailPattern = "^[a-zA-Z0-9._%+-]+@gmail\\.com$";

        if (email.matches(emailPattern)) {
            txtMailInsertUserForm.setBackground(Color.GREEN);
            habilitarBotonRegistro();
        } else {
            JOptionPane.showMessageDialog(this, "El correu electrònic introduit no és vàlid. Ha de ser una direcció de correu de Gmail.", "Error de Validació", JOptionPane.ERROR_MESSAGE);
            txtMailInsertUserForm.setBackground(Color.WHITE);
            deshabilitarBotonRegistro();
        }
    }//GEN-LAST:event_txtMailInsertUserFormFocusLost

    private void txtSurnameInsertUserFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSurnameInsertUserFormFocusLost
        String surname = txtSurnameInsertUserForm.getText().trim();
    
        if (surname.matches("^[a-zA-Z]+")) {
            txtSurnameInsertUserForm.setBackground(Color.GREEN);
            habilitarBotonRegistro();
        } else {
            JOptionPane.showMessageDialog(this, "El cognom introduit no és vàlid. Ha de contenir només lletres.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            txtSurnameInsertUserForm.setBackground(Color.WHITE);
            deshabilitarBotonRegistro();
        }
    }//GEN-LAST:event_txtSurnameInsertUserFormFocusLost

    private void txtNameInsertUserFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameInsertUserFormFocusLost
        String name = txtNameInsertUserForm.getText().trim();
    
        if (name.matches("^[a-zA-Z]+")) {
            txtNameInsertUserForm.setBackground(Color.GREEN);
            habilitarBotonRegistro();
        } else {
            JOptionPane.showMessageDialog(this, "El nom introduit no és vàlid. Ha de contenir només lletres.", "Error de Validació", JOptionPane.ERROR_MESSAGE);
            txtNameInsertUserForm.setBackground(Color.WHITE);
            deshabilitarBotonRegistro();
        }
    }//GEN-LAST:event_txtNameInsertUserFormFocusLost

    private void txtPasswdInsertUserFormFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswdInsertUserFormFocusLost
        String password = txtPasswdInsertUserForm.getText().trim();
    
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El camp de la contrasenya no pot quedar buit.", "Error de Validació", JOptionPane.ERROR_MESSAGE);
            txtPasswdInsertUserForm.setBackground(Color.RED);
            deshabilitarBotonRegistro();
        } else {
            txtPasswdInsertUserForm.setBackground(Color.GREEN);
            habilitarBotonRegistro();
        }
    }//GEN-LAST:event_txtPasswdInsertUserFormFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminNewUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminNewUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminNewUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminNewUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminNewUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInsertUserForm;
    public javax.swing.JButton btnReturnUserPanelActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtDniInsertUserForm;
    public javax.swing.JTextField txtMailInsertUserForm;
    public javax.swing.JTextField txtNameInsertUserForm;
    public javax.swing.JTextField txtPasswdInsertUserForm;
    public javax.swing.JTextField txtPhoneInsertUserForm;
    public javax.swing.JTextField txtSurnameInsertUserForm;
    // End of variables declaration//GEN-END:variables
}
