
package Views;

import Controllers.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class adminUsersDashboard extends javax.swing.JFrame {

    /**
     * Creates new form insertForm
     */
    public adminUsersDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
        tblUsers.setModel(modelo);
        PrincipalController.loadTblUser(modelo);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackUser = new javax.swing.JButton();
        txtSearchUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnInsertUserForm = new javax.swing.JButton();
        btnUpdateUserForm = new javax.swing.JButton();
        btnResetPasswdUserForm = new javax.swing.JButton();
        btnActivateUserForm = new javax.swing.JButton();
        btnDeactivateUserForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 229, 255));

        jPanel1.setBackground(new java.awt.Color(204, 229, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(575, 445));

        btnBackUser.setBackground(new java.awt.Color(255, 255, 255));
        btnBackUser.setForeground(new java.awt.Color(30, 30, 30));
        btnBackUser.setText("Tornar ...");
        btnBackUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUserActionPerformed(evt);
            }
        });

        txtSearchUser.setBackground(new java.awt.Color(255, 255, 255));
        txtSearchUser.setForeground(new java.awt.Color(30, 30, 30));
        txtSearchUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearchUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchUserCaretUpdate(evt);
            }
        });
        txtSearchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyTyped(evt);
            }
        });

        tblUsers.setBackground(new java.awt.Color(153, 204, 255));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Cognom", "DNI", "Correu", "Telèfon", "Estat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setGridColor(new java.awt.Color(255, 255, 255));
        tblUsers.setSelectionBackground(new java.awt.Color(255, 255, 225));
        jScrollPane1.setViewportView(tblUsers);

        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Filtra per DNI:");

        btnInsertUserForm.setBackground(new java.awt.Color(255, 255, 255));
        btnInsertUserForm.setForeground(new java.awt.Color(30, 30, 30));
        btnInsertUserForm.setText("Agregar");
        btnInsertUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnInsertUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertUserFormActionPerformed(evt);
            }
        });

        btnUpdateUserForm.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateUserForm.setForeground(new java.awt.Color(30, 30, 30));
        btnUpdateUserForm.setText("Modificar");
        btnUpdateUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdateUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserFormActionPerformed(evt);
            }
        });

        btnResetPasswdUserForm.setBackground(new java.awt.Color(255, 255, 255));
        btnResetPasswdUserForm.setForeground(new java.awt.Color(30, 30, 30));
        btnResetPasswdUserForm.setText("Resetejar Passwd");
        btnResetPasswdUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnResetPasswdUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswdUserFormActionPerformed(evt);
            }
        });

        btnActivateUserForm.setBackground(new java.awt.Color(255, 255, 255));
        btnActivateUserForm.setForeground(new java.awt.Color(30, 30, 30));
        btnActivateUserForm.setText("Activar");
        btnActivateUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActivateUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateUserFormActionPerformed(evt);
            }
        });

        btnDeactivateUserForm.setBackground(new java.awt.Color(255, 255, 255));
        btnDeactivateUserForm.setForeground(new java.awt.Color(30, 30, 30));
        btnDeactivateUserForm.setText("Desactivar");
        btnDeactivateUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDeactivateUserForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateUserFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBackUser, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSearchUser))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnResetPasswdUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDeactivateUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActivateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetPasswdUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActivateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeactivateUserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeactivateUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            System.out.print(selectedRow);
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            PrincipalController.deactivateUser(idUser);
            loadTable();
        }
    }//GEN-LAST:event_btnDeactivateUserFormActionPerformed

    private void btnActivateUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            System.out.print(selectedRow);
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            PrincipalController.activateUser(idUser);
            loadTable();
        }
    }//GEN-LAST:event_btnActivateUserFormActionPerformed

    private void btnBackUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUserActionPerformed
        PrincipalController.returnUserPanel();
    }//GEN-LAST:event_btnBackUserActionPerformed

    private void btnInsertUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertUserFormActionPerformed
        PrincipalController.showNewFormUserPanel();
    }//GEN-LAST:event_btnInsertUserFormActionPerformed

    private void btnUpdateUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            String nom = (String) modelTable.getValueAt(selectedRow, 1);
            String cognom = (String) modelTable.getValueAt(selectedRow, 2);
            String correu = (String) modelTable.getValueAt(selectedRow, 4);
            String telefon = (String) modelTable.getValueAt(selectedRow, 5);
            
            PrincipalController.showUpdateFormUserPanel(idUser, nom, cognom, correu, telefon);
        }
        
    }//GEN-LAST:event_btnUpdateUserFormActionPerformed

    private void btnResetPasswdUserFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswdUserFormActionPerformed
        if (tblUsers.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(null, "No s'ha seleccionat cap fila");
        else {
            DefaultTableModel modelTable = (DefaultTableModel) tblUsers.getModel();
            int selectedRow = tblUsers.getSelectedRow();
            System.out.print(selectedRow);
            int idUser =  (int) modelTable.getValueAt(selectedRow, 0);
            PrincipalController.resetPasswdUser(idUser);
        }
    }//GEN-LAST:event_btnResetPasswdUserFormActionPerformed

    private void txtSearchUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchUserCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserCaretUpdate

    private void txtSearchUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserKeyTyped

    private void txtSearchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyReleased
        DefaultTableModel modelo = new DefaultTableModel();
        tblUsers.setModel(modelo);
        String where = txtSearchUser.getText();
        PrincipalController.loadTblUserWhere(modelo, where);
    }//GEN-LAST:event_txtSearchUserKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminUsersDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminUsersDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivateUserForm;
    public javax.swing.JButton btnBackUser;
    public javax.swing.JButton btnDeactivateUserForm;
    public javax.swing.JButton btnInsertUserForm;
    public javax.swing.JButton btnResetPasswdUserForm;
    private javax.swing.JButton btnUpdateUserForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblUsers;
    public javax.swing.JTextField txtSearchUser;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        DefaultTableModel modelo = new DefaultTableModel();
        tblUsers.setModel(modelo);
        PrincipalController.loadTblUserWhere(modelo, txtSearchUser.getText());
    }
}
